blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Quick Questions or Brainstorming
    url: https://github.com/Cxsmxnaut/Gradely-Issues/discussions
    about: For open-ended questions, ideas, or announcements â€” use Discussions
